# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iXpenses2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxDataSources', '~> 5.0'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxBiBinding', '~>  0.3.5'
  pod 'Action', '~> 4.3.0'
  pod 'Reusable'
  pod 'Closures'
  pod 'RxGesture', '~> 4.0'
  pod 'NSObject+Rx', '~> 5.2.0'
  pod 'RxKeyboard', '~> 2.0'
  
  pod 'RxSwiftExt', '~> 6.0.0'
  
  pod 'ObjectMapper', '~> 3.5'
  
  pod 'lottie-ios'
  pod 'PanModal'
  pod 'MarkdownView'
  pod 'SwiftEntryKit', '1.2.7'
  pod 'Defaults'
  # pod 'XCoordinator/RxSwift', '~> 2.0'
  # Pods for iXpenses2
  pod 'Codextended'

end

